//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROYECTO_FINALEntities1 : DbContext
    {
        public PROYECTO_FINALEntities1()
            : base("name=PROYECTO_FINALEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARGO> CARGOes { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTOS { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOS { get; set; }
        public virtual DbSet<NOMINA> NOMINAS { get; set; }
        public virtual DbSet<SALIDA> SALIDAS { get; set; }
        public virtual DbSet<VACACIONE> VACACIONES { get; set; }
    }
}
